### ISSUE TITLE
Playership's type keeps changing to `Spacial` rather than what it needs to be, `KinematicBody`

### ISSUE THREAD

**Issue by gillett-hernandez** [infinityshelf/octo-blossom-godot#7]

**Comment by toiletsnakes** [comment]
I haven't gotten this in a while, will keep an eye on it

**Comment by gillett-hernandez** [comment]
fixed i think. it was the type that was saved within the `PlayerShip.scn/tscn` that kept changing it whenever you reloaded the scene. changing it within there and saving the scene fixed it
